title = 'keepSTEEP'
baseURL = 'https://oudon-mizusawa.github.io/keepSTEEP/'
languageCode = 'ja'
theme = "ananke"

DefaultContentLanguage = "ja"
SectionPagesMenu = "master"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "oudon"
  favicon = "img/logo.png"
  description = "ｽﾞｲ₍₍(ง˘ω˘)ว⁾⁾ｽﾞｲ"
  background_color_class = "bg-navy"
  recent_posts_number = 3

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/oudon-mizusawa"